### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by israel-lpz** [fancyapps/ui#112]
I have wanted to use it in a project with typescript and I have encountered the problem that it does not have Declaration Files or an npm @types package :(

**Comment by fancyapps** [comment]
Hi,

Have you tried creating .d.ts Files from .js files? https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by israel-lpz** [comment]
Yes, But not working for me

**Comment by steve3d** [comment]
@fancyapps 

create `.d.ts` using this way will create so many junk, like these

```
declare namespace defaults {
```

this `defaults` namespace is just a useless and is a very strange way of typescript declaration.

and I see your codes are written by es6 syntax, maybe you should consider use typescript to write the code and compile to esm, umd, and even es2019.

if this is not the way, then we need a correct typescript definition files and put this file in packages.json file, otherwise our typescript project still can not use it directly. and this is how threejs doing the typescript thing.

**Comment by steve3d** [comment]
@fancyapps  I have created a simple version of typescript definitions, but I'm not sure if all the functions should be exposed to typescript.

Should I create a PR?

**Comment by fancyapps** [comment]
@steve3d Sure, I would like to take a look.

**Comment by steve3d** [comment]
@fancyapps I've submitted the PR #243 , you might need to revise these.

**Comment by tech-goldenphoenix** [comment]
Are there any updates on this issue?

**Comment by fancyapps** [comment]
@tech-goldenphoenix I am very sorry, but it is not humanly possible to work on the two major versions at the same time while also providing support. You can check out steve3d's kindly provided PR or you'll have to wait for the next major version. If you are curious about the progress, then it is going quite well, I have already migrated Base and Panzoom components to TypeScript while also improving existing functionality and adding new features. Now I am working on revamping Carousel component.

**Comment by jacobgraf** [comment]
How's this coming along? We love FancyApps, but TS is a non-negotiable for us. I don't wanna have to find another package to use if TS support is right around the corner?

**Comment by fancyapps** [comment]
Hi, Fancybox5 has been available for some time and comes with TS types.

**Comment by jacobgraf** [comment]
So happy to hear! Thank you!
