### ISSUE TITLE
Question on architecture

### ISSUE THREAD

**Issue by lionel-dieu** [fancyapps/ui#207]
Hello,
Do you have a specific reason why default PANZOOM.CSS-definitions are NOT 'included' in FANCYBOX.CSS, while PANZOOM.JS-functionality is 'included' as part of FANCYBOX.JS ?
Many thanks.

**Comment by fancyapps** [comment]
Hi,

The relationship between all 3 components is as follows:

1) Panzoom provides gestures and panning, zooming functionality;
2) Carousel is build on top of the Panzoom; if you think about it, it just makes sense, because you can create a basic carousel by simply disabling zoom functionality and locking panning direction;
3) And if you take a look at Fancybox (or any other lightbox tool), it looks and feels like big carousel. Therefore it just made sense to build it on top the Carousel component. 
4) Also, Fancybox image plugin creates new Panzoom instance for each image in the carousel to provide touch gestures, zooming, etc.

As you can see, all components are related. But it would be great to use all 3 on one page, right? Therefore they use different class names and you can, for example, choose to use Panzoom and to style it without affecting Fancybox. But not everyone would want to do that, therefore panzoom.css is not included in fancybox.css to save some bytes.

**Comment by lionel-dieu** [comment]
Many thanks.
