### ISSUE TITLE
Make container draggable when using fit:contain-w

### ISSUE THREAD

**Issue by ArchimidisM** [fancyapps/ui#252]
Well I do not know if this is a noob question however I would like to open the image to a fullscreen mode. When I choose the fit to be "contain-w" well the draggable does not work and it shows a second scrollbar as well . Is there any work around?

**Comment by fancyapps** [comment]
Hi,

Sorry, there are currently no option for that and container is supposed to become scrollable by design. But it is planned to implement image handling differently in v5, then container will be draggable by default (work is currently underway, I can't give any ETA, but it won't be ready any time soon).

**Comment by ArchimidisM** [comment]
Oh I really appreciate your answer!!!
Btw as you already may know, fancybox is one of the best plugins out there :)
