### ISSUE TITLE
Dynamic change Carousel options

### ISSUE THREAD

**Issue by duannx** [fancyapps/ui#270]
Hi, I would like to know is there any way to dynamic update Carousel options and re-render the slider. Now I'm manually updating the options property and then calling `updatePage()` method. It works but I don't know if it is the official way and does not create any side effects.
```js
carouselInstance.options.slidesPerPage = 3
carouselInstance.value.updatePage()
```
By the way, my goal is to change the slidesPerPage based on the screen size. So a `breakpoints` option is nice to have.

**Comment by fancyapps** [comment]
Hi,

Sorry, buy why do you need to change `slidesPerPage` dynamically? Default value for that option is `auto` and what that means - you can have any width for the slide (`.carousel__slide`) elements and carousel will automatically read the rendered size and calculate width of each page based on number of slides that fits inside viewport. So, I don't think the 'breakpoint' option is needed, because can control the number of visible slides using CSS and that gives you more flexibility.

Anyway, `updatePage()` method is a preferred way to update the instance.

**Comment by tech-goldenphoenix** [comment]
Hi, thank you for clarifying that. I did not know that `slidesPerPage: 'auto'` can do the job. I come from another slider library's perspective when `slidesPerPage` actually controls the number of slides per page. Using CSS is a good idea. Maybe you should update the docs to point out that to prevent misunderstanding from other developers.

**Comment by duannx** [comment]
Hi, thank you for clarifying that. I did not know that slidesPerPage: 'auto' can do the job. I come from another slider library's perspective when slidesPerPage actually controls the number of slides per page. Using CSS is a good idea. Maybe you should update the docs to point out that to prevent misunderstanding from other developers.
