### ISSUE TITLE
zoom not working on iphone

### ISSUE THREAD

**Issue by kubiqsk** [fancyapps/ui#277]
Hi,
if I try to zoom image on your website in opened fancybox (https://fancyapps.com/docs/ui/fancybox/#quick-demo):

on Android - everything works as expected

on iPhone - when you pinch and zoom it will get smaller again instantly when you stop touching screen - also double tap to zoom is not working

**Comment by fancyapps** [comment]
>> also double tap to zoom is not working

Why do think it should zoom on double tap? It should not.

Anyway, the problem with the latest Safari is that Apple decided to move toolbar to the bottom and dynamically change viewport height. That causes content resizing and centering, because the script was created before Apple decided to bring that "enchacement". This will be improved in the next major version when viewport height changes will not cause issues.

**Comment by kubiqsk** [comment]
> Why do think it should zoom on double tap? It should not.

because that's how it works in older versions and people are used to do it that way as it work similar also in Google Photos and other similar apps on phone

> Anyway, the problem with the latest Safari is that Apple decided to move toolbar to the bottom and dynamically change viewport height. That causes content resizing and centering, because the script was created before Apple decided to bring that "enchacement". This will be improved in the next major version when viewport height changes will not cause issues.

But it works with Fancybox v3 on every device - problem is only in Fancybox v4 - so the problem is definitely not in the phone os or browser... it's simply something in v4

**Comment by fancyapps** [comment]
Hi,

It should work fine on v5. If you experience any issue, please, post new issue.
