### ISSUE TITLE
Strange bug on iPhones 

### ISSUE THREAD

**Issue by eukraina** [fancyapps/ui#304]
The problem is here
https://codepen.io/andrew-zheludkov/pen/MWQBNYW
In few words on my IPhone 10 in Chrome, Safari or any other browser I see a blink effect while zooming an image.

**Comment by eukraina** [comment]
A video
https://youtube.com/shorts/bhGb-Sl173g?feature=share

**Comment by fancyapps** [comment]
Hi,

Well, I could write message to a trillion dollar company to fix their software, but they really do not care about web browser, because that does not make money.

Short story - there is nothing I can do here, the upcoming v5 will work completely differently to avoid such issue. Try using smaller image files.
