### ISSUE TITLE
Carousel calculates slidesPerPage wrong

### ISSUE THREAD

**Issue by duannx** [fancyapps/ui#318]
## Problem
When using `slidesPerPage: auto` with adding a `margin-right` to `.carousel__slide` the Carousel calculates the number of slides per page wrong. See this [JS Fiddle](https://jsfiddle.net/duannx/bms6Ldxv/2/)

### Actual behavior
The first page shows slides 1, 2, 3. After clicking the next button, the second page shows slides **3, 4, 5**

### Expected behavior
The first page shows slides 1, 2, 3. After clicking the next button, the second page shows slides **4, 5, 6**

**Comment by kylehaugland** [comment]
I don't think it's being calculated incorrectly, I think that is the expected behavior. Taking the last slide from an initial page and moving that slide first slot on the next page allows you to keep your bearings as you page through (I'm assuming).

However, I would also like to use your "expected behavior" above and never see the same slide repeated. Are there any easy ways to do this? Almost like we need an "auto+1" option for slidesPerPage.

**Comment by fancyapps** [comment]
Hi,

Please, check out the freshly released v5.0.0. It should work as expected.

**Comment by duannx** [comment]
@fancyapps Hi, thank you for releasing the new version. Is there any changelog document for it?

**Comment by fancyapps** [comment]
@duannx There are release/upgrade notes - https://fancyapps.com/resources/upgrading/ - but there are too many changes to cover them all, a book could be written. Simply take a fresh start, join discord server is you have a quick questions related to migrating - https://discord.gg/PtQum6Zr

**Comment by fancyapps** [comment]
I re-created your example using v5 and it works as expected - https://jsfiddle.net/e8jdxmv3/
