### ISSUE TITLE
Binding custom AJAX type doesn't work

### ISSUE THREAD

**Issue by nielsvr** [fancyapps/ui#327]
We are trying to run an AJAX request to show in a Fancybox modal;

```
Fancybox.bind('[data-book-activity]', {
	type: 'ajax',
	src: 'book.php',
	data: {
		'action' : 'book_activity', 
	}
});
```

The result is a AJAX request to it's own page, not the 'src' attribute. It also seems that data isn't posted. If we use the declaritive method;

`<a data-fancybox data-type='ajax' data-src='book.php'>book</a>`

It seems to work, but we can't seem to provide data attributes to POST and its not the prefferable way of using this.

**Comment by fancyapps** [comment]
Hi,

The correct way of using Fancybox is to attach click event to your element then use `Fancybox.show()` method to start Fancybox.

**Comment by cbeyer** [comment]
@fancyapps is it possible to have an example with code ?

**Comment by gobeyond-laura-speck** [comment]
@cbeyer Did you ever figure this out? Using the older version, I run the ajax call then on .done(function(result)), I would run $.fancybox.open(result, ..etc.

Trying to use Fancybox.show(), but it would seem I cannot POST the data to the src. It seems to default to GET. I can't use GET, because passing userdata.

And cannot seem to just pass my 'result' to the new Fancybox.

Did you ever figure out how to do it?
