### ISSUE TITLE
Boostratp 5 and fancy gallery no work

### ISSUE THREAD

**Issue by saturnov** [fancyapps/ui#332]
https://jsfiddle.net/0dev_babilonia0/Lfq3brmj/5/

**Comment by fancyapps** [comment]
Hi,

Your HTML code is not valid. You have to use smth like `htmlspecialchars()` to encode HTML content inside the caption.

**Comment by saturnov** [comment]
the problems is the position or z-index from modal bootstratp no the caption, if l change the position the key's no working fine.

**Comment by fancyapps** [comment]
You can set a lower z-index for the bootstrap or a higher for Fancybox (like `.fancybox__container {  z-index: 99999; }`). For the key navigation, you have to disable keyboard listening for Bootstrap.

**Comment by saturnov** [comment]
https://jsfiddle.net/0dev_babilonia0/Lfq3brmj/12/
 l change the z-index and see fine . but the key no work , its' for the focus or there is another way ?

**Comment by fancyapps** [comment]
Both modals listen to keyboard events, because they do not know if there is another modal already open. Therefore, if you want to use keyboard events for Fancybox, you have to disable (by yourself) to Bootstrap modal. Or simply replace Bootstrap modal with Fancybox, because Fancybox supports multiple open instances.
