### ISSUE TITLE
Use esacpe key to close iframe Fancybox

### ISSUE THREAD

**Issue by tin-soldier** [fancyapps/ui#398]
I may be missing something but it doesn't seem possible to close an Fancybox modal if it's content is an iframe.

Have added the keyboard options but maybe this is incorrect?

https://codesandbox.io/s/fancybox-iframe-forked-sx8g82?file=/src/index.js

**Comment by fancyapps** [comment]
Hi,

Due to the browser's security policy, once focus is inside an iFrame, keyboard events stay here. Imagine what a security breach it would be if you placed a page in an iframe and you could read the entered usernames, passwords, etc.

The only solution is to listen keyboard events inside the iframed page and then close fancybox like this: `window.parent.Fancybox.close()` (or to use `window.parent.postMessage()` to communicate with parent page).
