### ISSUE TITLE
if ($.fancybox.isMobile) {   $.fancybox.destroy(); }

### ISSUE THREAD

**Issue by alecos71** [fancyapps/ui#409]
is it possible to have like version 3 of fancybox?

```
if ($.fancybox.isMobile) {
  $.fancybox.destroy();
}
```

**Comment by alecos71** [comment]
I need to exclude loading fancybox 5 in some page where the device is mobile...

thanks

**Comment by fancyapps** [comment]
Hi,

Actually, v5 does not auto-bind, you have to call `Fancybox.bind()` to enable Fancybox. So all you have to do is to have smth like this:

```js
if (!/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
   Fancybox.bind('[data-fancybox]');
}
```

**Comment by alecos71** [comment]
It's possible to add to the feature plan Fancybox.destroy() with possibility to check mobile device like previous version 3 of fancybox?

Thanks.

Kind regards

**Comment by fancyapps** [comment]
You know, this is the actual code for mobile detection in v3 - `/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)` :)

It used to enable "mobile" mode, but v5 has something similar called "compact" mode. Because nowadays JS can run on anything even a fridge. And the fridge is not really a mobile device, but it would probably have a small screen :)

**Comment by alecos71** [comment]
Thanks
