### ISSUE TITLE
react-scripts build fails with a 'syntax error' in carousel.css

### ISSUE THREAD

**Issue by sahithreddya** [fancyapps/ui#431]
### Describe the bug

I integrated the Fancybox and Carousel components to my application. The application runs well but when I try to run react-scripts build, the build fails with below error -

```
Creating an optimized production build...
Failed to compile.

./node_modules/@fancyapps/ui/dist/carousel/carousel.css
ParserError: Syntax Error at line: 1, column 36


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sahith.reddy@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
```

--

### Reproduction

Link to Cloud sandbox with carousel code → https://codesandbox.io/p/sandbox/fancyapp-react-build-error-reproduction-gzpr40?welcome=true

---

I ran the carousel code in a browser sandbox environment using codesandbox.io, and it worked as expected as seen below

![image](https://user-images.githubusercontent.com/25284768/222933286-b2bb628f-e571-4878-af19-b7c6e81b5099.png)

In order to trigger a build through the sandbox terminal, I converted to cloud sandbox as it is not possible in the browser sandbox. (refer to below image)
![image](https://user-images.githubusercontent.com/25284768/222933352-f74e4d7a-d56f-4379-83df-4ce95cf3a02f.png)

After running the same code in the cloud sandbox, and the build was triggered in the terminal, the build failed as seen in the below image. The cloud sandbox was trying to create its own build to run the app, but it failed with the same error I was getting in my local environment.

![image](https://user-images.githubusercontent.com/25284768/222934246-9517f0b6-cb56-4ada-a4d7-3c81174831b6.png)

### Validations

- [X] Read the [docs](https://fancyapps.com/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sahithreddya** [comment]
P.S. : I forgot to update **_class_** to **_className_** while copying the carousel code from docs and taking the screenshots, the sandbox link has the right syntax. It doesn't affect the output in any way.

**Comment by fancyapps** [comment]
Hi,

First of all, that error message is completely misleading because **there are no errors in the CSS file**. It simply cannot have any syntax errors because it is built internally from "scss" files using the latest Dart Sass. If you still think there is an error in it, please file a bug report here https://github.com/sass/dart-sass

So, either fix your tools or include the CSS files directly in your page. (using `<link rel=...`). react-scripts haven't been updated in over a year, have a lot of issues (more than 1.5k), and even the authors encourage you not to use it.
