### ISSUE TITLE
Reload causes UI init problems

### ISSUE THREAD

**Issue by amkdev** [fancyapps/ui#6]
For my galleries I took the "Facebook inspired design, thumbnail images for background" example from the showcase.

This works very well but on reloading the page, when fancybox opens again by itself, the UI is broken and the background are gone.

**Comment by fancyapps** [comment]
Hi,

Could you, please, create a demo where your issue could be inspected? I am not able to reproduce this issue.

**Comment by amkdev** [comment]
I put my fancybox test branch online

open the first image and reaload 
https://fancyphotos.alexander-korn.de/de/__home__/india-2014/neu-delhi

or open this link
https://fancyphotos.alexander-korn.de/de/__home__/india-2014/neu-delhi#gallery-1

**Comment by fancyapps** [comment]
The possible cause is that your JS code is executing with a delay, e.g., Hash plugins starts Fancybox before your JS code (that customizes Fancybox) has finished processing. Since your links do not work anymore, I am not able to check your code.

If anyone else is experiencing this issue, please, comment here and I will look into this again.
