### ISSUE TITLE
How to close fancebox?

### ISSUE THREAD

**Issue by andryshok** [fancyapps/ui#610]
### Describe the bug

I have issue - Fancybox is not defined. 

### Reproduction

I use RESPONSIVE filemanager from [https://www.responsivefilemanager.com/](url)
In the version 3 of fancybox after select file in RESPONSIVE filemanager (opened with fancybox)   fancybox closed with this code - 
`parent.jQuery.fancybox.close()`
Now, i use fancybox 5 and method
`Fancybox.close();`  now working , issue - Fancybox is not defined. How fix it?

**Comment by fancyapps** [comment]
Hi,

Close Fancybox from the iframed page using `window.parent.Fancybox.close();`, example:

```html
<p>
      <button onclick="window.parent.Fancybox.close();">Close this iframe</button>
</p>
```

**Explanation**

Let's break down the previous code `parent.jQuery.fancybox.close()`:

`parent` - reference to the parent of the current window https://developer.mozilla.org/en-US/docs/Web/API/Window/parent
`jQuery` - reference to jQuery; NO longer NEEDED, because Fancybox 4+ does not have jQuery as a dependency.
`fancybox` - reference to `fancybox`; following the new naming convention, it now begins with a capital letter, use `Fancybox`
`close()` - static method of the Fancybox; see https://fancyapps.com/fancybox/api/methods/#methods
