### ISSUE TITLE
Fancybox insert linebreak

### ISSUE THREAD

**Issue by IMC-GER** [fancyapps/ui#97]
Hi,

in the HTML dialogbox Fancybox insert after some closing tags `(</b>, </strong>, </span> usw.)` a linebreak.

Only inside the paragraph element it works correct.

https://fancyapps.com/playground/HS

**Comment by fancyapps** [comment]
Hi,

Fancybox is not adding anything. As you correctly pointed out, your issue arises due to invalid HTML markup. Since Fancybox adds `display:flex` by default to hidden elements, browsers will format your markup with unexpected results.

The solution would be to either use correct markup or to change display to "block", simply add `data-display="block"` to your link, demo:

https://fancyapps.com/playground/Id

**Comment by IMC-GER** [comment]
Hi,

Thank you for the explanation.
I adjusted my code.
